/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitaRouteImport } from './routes/visita'
import { Route as QuestionarioRouteImport } from './routes/questionario'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PianoRouteImport } from './routes/piano'
import { Route as CompletatoRouteImport } from './routes/completato'
import { Route as ComeFunzionaRouteImport } from './routes/come-funziona'
import { Route as IndexRouteImport } from './routes/index'

const VisitaRoute = VisitaRouteImport.update({
  id: '/visita',
  path: '/visita',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionarioRoute = QuestionarioRouteImport.update({
  id: '/questionario',
  path: '/questionario',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PianoRoute = PianoRouteImport.update({
  id: '/piano',
  path: '/piano',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletatoRoute = CompletatoRouteImport.update({
  id: '/completato',
  path: '/completato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComeFunzionaRoute = ComeFunzionaRouteImport.update({
  id: '/come-funziona',
  path: '/come-funziona',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/come-funziona': typeof ComeFunzionaRoute
  '/completato': typeof CompletatoRoute
  '/piano': typeof PianoRoute
  '/privacy': typeof PrivacyRoute
  '/questionario': typeof QuestionarioRoute
  '/visita': typeof VisitaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/come-funziona': typeof ComeFunzionaRoute
  '/completato': typeof CompletatoRoute
  '/piano': typeof PianoRoute
  '/privacy': typeof PrivacyRoute
  '/questionario': typeof QuestionarioRoute
  '/visita': typeof VisitaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/come-funziona': typeof ComeFunzionaRoute
  '/completato': typeof CompletatoRoute
  '/piano': typeof PianoRoute
  '/privacy': typeof PrivacyRoute
  '/questionario': typeof QuestionarioRoute
  '/visita': typeof VisitaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/come-funziona'
    | '/completato'
    | '/piano'
    | '/privacy'
    | '/questionario'
    | '/visita'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/come-funziona'
    | '/completato'
    | '/piano'
    | '/privacy'
    | '/questionario'
    | '/visita'
  id:
    | '__root__'
    | '/'
    | '/come-funziona'
    | '/completato'
    | '/piano'
    | '/privacy'
    | '/questionario'
    | '/visita'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComeFunzionaRoute: typeof ComeFunzionaRoute
  CompletatoRoute: typeof CompletatoRoute
  PianoRoute: typeof PianoRoute
  PrivacyRoute: typeof PrivacyRoute
  QuestionarioRoute: typeof QuestionarioRoute
  VisitaRoute: typeof VisitaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visita': {
      id: '/visita'
      path: '/visita'
      fullPath: '/visita'
      preLoaderRoute: typeof VisitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionario': {
      id: '/questionario'
      path: '/questionario'
      fullPath: '/questionario'
      preLoaderRoute: typeof QuestionarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piano': {
      id: '/piano'
      path: '/piano'
      fullPath: '/piano'
      preLoaderRoute: typeof PianoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completato': {
      id: '/completato'
      path: '/completato'
      fullPath: '/completato'
      preLoaderRoute: typeof CompletatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/come-funziona': {
      id: '/come-funziona'
      path: '/come-funziona'
      fullPath: '/come-funziona'
      preLoaderRoute: typeof ComeFunzionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComeFunzionaRoute: ComeFunzionaRoute,
  CompletatoRoute: CompletatoRoute,
  PianoRoute: PianoRoute,
  PrivacyRoute: PrivacyRoute,
  QuestionarioRoute: QuestionarioRoute,
  VisitaRoute: VisitaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
